### PR TITLE
Update meta.yaml

### PR DESCRIPTION
**Pull request by knaaptime**
update pins

### CODE REVIEW

**Comment by jGaboardi** [comment]
@knaaptime Looks like this was never merged. Should probably enable [auto merge](https://conda-forge.org/docs/maintainer/infrastructure.html#conda-forge-admin-please-add-bot-automerge) here.

**Comment by knaaptime** [comment]
@conda-forge-admin, please add bot automerge

**Comment by knaaptime** [comment]
ugh

**Review by jGaboardi — APPROVED** [review]

**Comment by jGaboardi** [comment]
@knaaptime I think we can simply merge this?

**Pull request merged**
